apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: counter-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: counter-app
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50